# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-bitsailor

# >> macros
# << macros
%define _binary_payload w2.xzdio

Summary:    BitSailor
Version:    1.5.1
Release:    1
Group:      Applications/Productivity
License:    MIT
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2

%{!?harbour_store:%define harbour_store %(if [ -n "$HARBOUR_STORE" ]; then echo 1; elif echo "$PWD" | grep -q -- '-Store'; then echo 1; else echo 0; fi)}

%if 0%{?harbour_store}
%global __provides_exclude_from ^%{_datadir}/%{name}/lib/.*$
%global __requires_exclude_from ^%{_datadir}/%{name}/lib/.*$
%global __requires_exclude ^libbw\\.so$|^libbw\\.so\\(\\)\\(64bit\\)$
%endif

Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   sailfishsecretsdaemon-secretsplugins-default
%if 0%{?harbour_store} == 0
Requires:   sailfish-polkit-agent
%endif
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(sailfishsecrets)
BuildRequires:  pkgconfig(sailfishcrypto)
BuildRequires:  desktop-file-utils

%description
A Sailfish OS Bitwarden client


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%if 0%{?harbour_store}
%qmake5 CONFIG+=harbour_store
%else
%qmake5
%endif

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
%if 0%{?harbour_store}
sed -i \
  -e '/^Sandboxing=Disabled$/d' \
  -e 's|^Permissions=.*|Permissions=Internet;Secrets;UserDirs|' \
  %{buildroot}%{_datadir}/applications/%{name}.desktop
rm -f %{buildroot}%{_datadir}/%{name}/qml/components/GeneratePasswordTabs.qml
%endif

strip --strip-unneeded %{buildroot}%{_datadir}/%{name}/lib/libbw.so

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%if 0%{?harbour_store} == 0
%{_datadir}/polkit-1/actions/cz.chrastecky.bitsailor.policy
%{_datadir}/dbus-1/services/cz.chrastecky.bitsailor.service
%endif
# >> files
# << files
