name: Update Translations

on:
  pull_request:
    branches:
      - master
#    paths:
#      - 'translations-other/*'

jobs:
  update_translations:
    runs-on: ubuntu-latest
    name: Update Translations
    steps:
      - name: Debug
        run: |
          echo $GITHUB_HEAD_REF
      - uses: actions/checkout@v2
        name: Checkout
      - name: Update Desktop File
        run: php translations-other/update-translations.php
      - name: Update
        uses: actions-x/commit@v6
        with:
          message: Updated desktop and polkit files
          branch: ${{ github.head_ref }}
