name: Update Translations

on:
  pull_request:
    branches:
      - master
    paths:
      - 'translations-other/*'

jobs:
  update_translations:
    runs-on: ubuntu-latest
    name: Update Translations
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Update Desktop File
        run: php translations-other/update-translations.php
      - name: Commit
        run: |
          git config --global user.email "github-bot@localhost"
          git config --global user.name "Github Bot"
          git fetch
          git checkout ${{ github.head_ref }}
          git add . -v
          git commit -m "Updated desktop and polkit files"
          git push origin ${{ github.head_ref }}
